spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: instancia3
server:
  port: 9000

